title: jpvillaisaza
author: Juan Pedro Villa Isaza

permalink: pretty
lang: en
timezone: America/Bogota

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor

include: [_pages]

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
