title: jpvillaisaza

permalink: pretty
lang: en
timezone: America/Bogota

collections:
  recipes:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
      layout: "post"
  -
    scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"

exclude:
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
