title: jpvillaisaza
author: Juan Pedro Villa Isaza

permalink: pretty
lang: en
timezone: America/Bogota

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
      layout: "post"

exclude:
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
