title: jpvillaisaza
author: Juan Pedro Villa Isaza

permalink: pretty
lang: en
timezone: America/Bogota

exclude:
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor

include: [_pages]

plugins:
- jekyll-seo-tag
- jekyll-sitemap
