title: jpvillaisaza

permalink: pretty
timezone: America/Bogota

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
      layout: "post"

exclude:
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
