version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run:
          command: bundle check || bundle install
      - run:
          name: jekyll build
          command: bundle exec jekyll build
      - run:
          name: htmlproofer ...
          command: |
            bundle exec htmlproofer ./_site \
              --check-favicon \
              --check-html
