name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 1 * *'

jobs:
  build:
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    runs-on: macos-latest
    defaults:
      run:
        working-directory: docs
    steps:
    - name: Run checkout
      uses: actions/checkout@v3
    - run: bundle config path vendor/bundle
    - run: bundle lock
    - uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        path: vendor/bundle
        restore-keys: |
          ${{ runner.os }}-gems-
    - run: bundle check || bundle install
    - run: bundle exec jekyll build
    - run: bundle exec github-pages health-check
