name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - run: bundle --version
    - run: bundle check || bundle install      
    - run: bundle exec jekyll build

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
