name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - run: bundle check || bundle install      
    - run: bundle exec jekyll build
    - run: |
        bundle exec htmlproofer _site \
          --check-favicon \
          --check-html \
          --disable-external
