name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    runs-on: macos-latest
    steps:
    - name: Run checkout
      uses: actions/checkout@v2
    - run: bundle check || bundle install
    - run: bundle exec jekyll build
    - name: Run htmlproofer
      run: |
        bundle exec htmlproofer _site \
          --check-favicon \
          --check-html \
          --disable-external
