name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '30 5 * * 6'

jobs:
  build:
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    runs-on: macos-latest
    steps:
    - name: Run checkout
      uses: actions/checkout@v2
    - run: bundle config path vendor/bundle
    - run: bundle lock
    - uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        path: vendor/bundle
        restore-keys: |
          ${{ runner.os }}-gems-
    - run: bundle check || bundle install
    - run: bundle exec jekyll build
    - name: Run htmlproofer
      run: |
        bundle exec htmlproofer _site \
          --check-favicon \
          --check-html \
          --disable-external
    - run: bundle exec github-pages health-check
